# Generated by Django 4.1.4 on 2023-01-21 18:24

from django.db import migrations, models
import django.db.models.deletion
import django_ulid.models
import location_field.models.plain
import pendulum
import spendium.models
import utilities.modelfields
import utilities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=spendium.models.new_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    utilities.modelfields.PendulumDateTimeField(default=pendulum.now),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "location",
                    location_field.models.plain.PlainLocationField(
                        default="40.17887331434696,-95.625", max_length=63
                    ),
                ),
                ("place_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "store_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=utilities.models.new_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    utilities.modelfields.PendulumDateTimeField(default=pendulum.now),
                ),
                ("currency", models.CharField(max_length=3)),
                ("payment_channel", models.CharField(max_length=10)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spendium.store"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
