# Generated by Django 4.1.4 on 2023-01-31 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pendulum
import utilities.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spendium", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="timestamp",
            field=utilities.modelfields.PendulumDateTimeField(default=pendulum.now),
        ),
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
