# Generated by Django 4.1.4 on 2022-12-28 05:01

from django.db import migrations, models
import django_ulid.models
import pendulum
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=pendulum.now)),
                ("name", models.CharField(max_length=250)),
                ("values", models.IntegerField(default=0)),
                ("allow_self_check_in", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=pendulum.now)),
            ],
        ),
    ]
