# Generated by Django 4.1.4 on 2022-12-30 04:20

from django.db import migrations, models
import django_ulid.models
import eventium.models
import pendulum
import utilities.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=eventium.models.new_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    utilities.modelfields.PendulumDateTimeField(default=pendulum.now),
                ),
                ("name", models.CharField(max_length=250)),
                ("values", models.IntegerField(default=0)),
                ("allow_self_check_in", models.BooleanField(default=True)),
                (
                    "finalized_at",
                    utilities.modelfields.PendulumDateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    utilities.modelfields.PendulumDateTimeField(default=pendulum.now),
                ),
            ],
        ),
    ]
