# Generated by Django 4.1.4 on 2023-01-21 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventium", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilities.category"
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eventium.event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
