# Generated by Django 4.1.4 on 2022-12-28 17:13

from django.db import migrations
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ("eventium", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=django_ulid.models.ULIDField(
                default=ulid.api.api.Api.new,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
