# Generated by Django 4.1.4 on 2022-12-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="event_check_in_cutoff_hours",
            field=models.IntegerField(
                default=2,
                help_text="How old in hours an event can still be checked in to",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="event_organizer_point_share",
            field=models.IntegerField(
                default=20, help_text="The percentage of all points the organizer earns"
            ),
        ),
    ]
