# Generated by Django 4.1.7 on 2023-05-01 17:01

from django.db import migrations
import utilities.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="last_updated_at",
            field=utilities.modelfields.PendulumDateTimeField(blank=True, null=True),
        ),
    ]
