# Generated by Django 4.1.4 on 2022-12-31 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ulid.models
import pendulum
import utilities.modelfields
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_configuration_event_check_in_cutoff_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="survey_expiration",
            field=models.IntegerField(
                default=7,
                help_text="Time, in days, before an offered survey can no longer be completed.",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="event_organizer_point_share",
            field=models.IntegerField(
                default=20,
                help_text="The percentage of all points the organizer of an event earns",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="survey_percentage",
            field=models.IntegerField(
                default=10,
                help_text="What percentage of users of this entity are offered a survey.",
            ),
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=utilities.models.new_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    utilities.modelfields.PendulumDateTimeField(default=pendulum.now),
                ),
                (
                    "completed_at",
                    utilities.modelfields.PendulumDateTimeField(blank=True, null=True),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilities.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
