# Generated by Django 4.1.4 on 2022-12-28 17:20

from django.db import migrations
import django_ulid.models
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_alter_activity_id_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=django_ulid.models.ULIDField(
                default=utilities.models.new_ulid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=django_ulid.models.ULIDField(
                default=utilities.models.new_ulid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="id",
            field=django_ulid.models.ULIDField(
                default=utilities.models.new_ulid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="hfuser",
            name="id",
            field=django_ulid.models.ULIDField(
                default=utilities.models.new_ulid,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
